[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.dependencies]
sqlx = { version = "0.7.4", features = [
    "runtime-tokio",
    "tls-rustls",
    "postgres",
    "migrate",
    "uuid",
    "macros",
    "rust_decimal",
    "chrono",
] }
chrono = "0.4.37"
